### ISSUE TITLE
Fix some content in the intro part

### ISSUE THREAD

**Issue by tipnareetes** [meeks21/g3-final#28]
Here is what we want to revise the intro text to say:

LAMP stack not fitting your needs? Try out a MERN stack! Using a combination of cutting-edge technologies, it just might be what you need to deliver a product that is set to impress.

MERN stands for:
MongoDB: a cross-platform document-oriented database program.
Express.js: a fast, free, open-source, and minimalist web framework for Node.js
React.js: a JavaScript front-end library developed by Facebook for building user interfaces.
Node.js: an open-source, cross-platform JavaScript run-time environment.

**Comment by amoryg** [comment]
LAMP stack not fitting your needs? Try out a MERN stack! Using a combination of cutting-edge technologies, it just might be what you need to deliver a product that is set to impress.

MERN stands for:
MongoDB: a cross-platform document-oriented database program.
Express.js: a fast, free, open-source, and minimalist web framework for Node.js
React.js: a JavaScript front-end library developed by Facebook for building user interfaces.
Node.js: an open-source, cross-platform JavaScript run-time environment.

The advantage to a MERN stack is that Express.js, React.js, and Node.js all use JavaScript. This allows the developer to use the same language from back-end to front-end. Even the database, MongoDB, uses a .json like file called .bson, which stands for bianary .json.
